### ISSUE TITLE
Appveyor builds with a wrong version of MVS

### ISSUE THREAD

**Issue by arokem** [conda-forge/dipy-feedstock#12]
According to @garyfallidis: it should be visual studio 15 and not 14. 

Does anyone on the @conda-forge/core team know how to make this happen?

**Comment by msarahan** [comment]
Vs 2015 is msvc 14. You're fine.

**Comment by arokem** [comment]
Thanks. Any ideas on the current Appveyor breakage?

**Comment by Garyfallidis** [comment]
To add here that on our windows machines we can compile dipy without errors using msvc 14.

**Comment by mwcraig** [comment]
What python version/machine architecture? 

I looks like the same issue has been occurring on any python that uses msvc 14 and 64 bit since almost the beginning of the feedstock (e.g. https://ci.appveyor.com/project/conda-forge/dipy-feedstock/build/1.0.5/job/7arob6vxu9736t37#L899)

I've hit something like that compiler error before, and worked around it by changing the appveyor build image because it seemed to be a bug introduced a service pack update of MSVC a while ago.

I was able to reproduce it locally at the time; see https://github.com/appveyor/ci/issues/891 for the report I submitted.

Please see if you can reproduce it on your windows machine. I won't have time to try on a Windows box before next week, and may not then, unfortunately....

**Comment by jakirkham** [comment]
I have seen some differences between using Python 3.5 and 3.6 even though they should use the same compiler version. Like `stdint` workarounds break with Python 3.6 and not Python 3.5. This happens with `pycrypto` for instance. Not sure if you are seeing anything like that here.

**Comment by mwcraig** [comment]
These seem to be consistently breaking on python 3.5 and 3.6 on x86_64....but working on x86.

**Comment by jakirkham** [comment]
Is it `int` related? If so, it is worth noting that 64-bit Windows uses 32-bit integers for `int`. Though maybe you already know this.

**Comment by jakirkham** [comment]
Another thing to try would be to disable all compiler optimizations. Might make the final code slow. However considering there is no 64-bit build currently, slow and present is better than none at all.

**Comment by jakirkham** [comment]
Would add the lines before that are pretty telling (snippet and link to log below). Is something getting redefined? If so, that seems worthy of investigating. Could be causing the linkage failure that crashes the build.

```
warning LNK4197: export 'PyInit_metricspeed' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.5\Release\dipy\segment\metricspeed.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\dipy\segment\metricspeed.cp35-win_amd64.exp
```

ref: https://ci.appveyor.com/project/conda-forge/dipy-feedstock/build/1.0.26/job/dllx1cbx07oxrf2n#L1701

**Comment by Garyfallidis** [comment]
Hi @msarahan @mwcraig and @jakirkham I am able to build the modules with no problem in my Windows 64 machine with python 3.6
I do have the same optimization flags /Ox and I get no issues. Same compiler too.  Could it be the service pack (build)?
I am on Windows 10 Enterprize, OS version 1607, build 14393.1358.

**Comment by mwcraig** [comment]
@Garyfallidis -- what is the build/service pack number for MSVC?

**Comment by Garyfallidis** [comment]
@mwcraig what is the best way to get this number?

**Comment by Garyfallidis** [comment]
I know those numbers Visual C++ 2015 (14.0)   MSC_VER=1900

![image](https://user-images.githubusercontent.com/134276/27699023-ebdece78-5cc6-11e7-909c-74fa1127c686.png)

**Comment by Garyfallidis** [comment]
@mwcraig and all. Was this information helpful? Apologies for the urgency. We just released and we would love to announce that our project can be installed with conda.

**Comment by mwcraig** [comment]
Putting out fires at the moment, will circle back around to this later
today :)

**Comment by jakirkham** [comment]
Maybe it would be worth checking what the version is on AppVeyor, @Garyfallidis? I don't know if this would be in the logs or the docs. If not in those places would raise an issue with AppVeyor directly to get that info. In any event, that seems like the next piece of info needed.

**Comment by arokem** [comment]
Does this provide the needed information?

https://www.appveyor.com/docs/build-environment/#visual-studio-2015

Should we try VS 2017?

**Comment by jakirkham** [comment]
> Should we try VS 2017?

I don't think this is an option as we have been trying to match runtimes to what CPython and wheels use.

**Comment by Garyfallidis** [comment]
Yes, we cannot use VS 2017. It needs to be matching the CPython version in the system and that is with VS 2015.

**Comment by Garyfallidis** [comment]
@arokem from the link that you shared I would select Visual Studio Community 2015 with Update 3. Is there an option somewhere in the configuration files of appveyor to choose this VS version?

Oh and @jakirkham when I run ``cl`` in the command line I get 19.00.24210.

**Comment by jakirkham** [comment]
Sounds like you are already getting the version you want then.

**Comment by arokem** [comment]
IIUC, this link indicates that when you use Visual Studio 2015, that is the
version that gets used.

I tried adding features on a new PR (#13). I have no idea what it means,
but it seems like a Windows thing, so maybe it will help?

**Comment by jakirkham** [comment]
Yeah features are unlikely to solve this problem. They seem really magical at first, but really they exist to do one thing. That is to align and attach the non-Python parts of the stack (e.g. OpenSSL) to the Python portions of the stack (e.g. PyOpenSSL) while ensuring the same Windows runtime is used by all of them. Python acts as the glue here. The Python portions don't need features as the Python version they are built with is already sufficient for uniquely specifying the runtime.

**Comment by jakirkham** [comment]
Honestly I'd raise an issue with AppVeyor and see if they have any advice. Though it might be tricky to solve. This passed once on AppVeyor ~1yr on the [very first build]( https://ci.appveyor.com/project/conda-forge/dipy-feedstock/build/1.0.1 ). The [very next build]( https://ci.appveyor.com/project/conda-forge/dipy-feedstock/build/1.0.5 ) fails. Since then it has failed on Windows 64-bit Python 3.5+ every time. So the cause is likely very old. Maybe they have some records that can help. If they can help you ssh into a machine, maybe you can find what you are looking for.

**Comment by mwcraig** [comment]
> This passed once on AppVeyor ~1yr on the very first build. The very next build fails. 

Right; these two builds straddle the release of Visual Studio Update 3 in late June 2016. Later tonight I'll try a local build of the year-old version later tonight but I'm willing to bet it will fail with the error we are seeing on appveyor. I suppose maybe we could try re-running the old build, which I'm guessing would fail now.

@Garyfallidis -- can you open visual studio from the command line, then go to Help → About Microsoft Visual Studio and report back what you see?

The bit in the yellow box is the important part.

![windows_7_64-bit](https://user-images.githubusercontent.com/1147167/27714308-ac370e64-5cf5-11e7-9e2d-bd7bbf5af844.png)

**Comment by Garyfallidis** [comment]
Hi @mwcraig and all, 

I think the following information would help resolve the issue. 
I figured out that what I have and making this compilation work is not the community edition but build tools.

I recently installed Visual Build tools 2015. These are available for download here
http://landinghub.visualstudio.com/visual-cpp-build-tools
You can try installing those in your machine and see if that works for you (you may need to remove other 2015 versions).

Important is also to make sure to check Windows 8.1 SDK and Windows 10 SDK options during installation. I would actually suggest when speaking to Appveyor to ask to have a full install just in case we miss something important (for example openmp support).

The setuptools Python package version must be at least 24.0 as explained here.
https://wiki.python.org/moin/WindowsCompilers

Moreover, in the appveyor listing that @arokem posted
https://www.appveyor.com/docs/build-environment/#visual-studio-2015
we have available
a) Visual Studio Community 2015 with Update 3
b) Python Tools for Visual Studio 2015

First option (a) didn't work for me when I tried it but it may work if we install some missing packages. But the safe choice seems to be build tools.
Option (b) works great for python 2.7 but not for 3+. So, we should ignore that something that I am sure you already know.

Do someone from the anaconda team want to take the lead in contacting appveyor to ask for making Visual Build tools available? Or we should make the call?

Let me know what you think and let me know also if Visual Build tools 2015 worked in your personal windows 10 machines.

**Comment by isuruf** [comment]
> I don't think this is an option as we have been trying to match runtimes to what CPython and wheels use.

FYI, MSVC 2015 and 2017 are backwards and forwards compatible, so that's not a problem.

**Comment by Garyfallidis** [comment]
I am not sure what you mean here @isuruf. You can make the following test. Install VS 17 and try to compile any cython module for 3.6 and you will see that it is not possible.  That looks like a problem to me.

**Comment by isuruf** [comment]
what kind of problems? Cython.distutils not supporting it?

**Comment by Garyfallidis** [comment]
To compile a cython module correctly you need to use the same compiler as the one used for creating specific python (cpython) that you use. That is for windows. In other OSs there is more flexibility.

**Comment by isuruf** [comment]
Yes, that is the case for previous MSVC compilers. MSVC 2017 is special and it's version is `14.1` while MSVC 2015 is `14.0` and Microsoft says that `14.x` series will be backwards and forwards ABI compatible with each other. https://blogs.msdn.microsoft.com/vcblog/2017/03/07/binary-compatibility-and-pain-free-upgrade-why-moving-to-visual-studio-2017-is-almost-too-easy/

**Comment by Garyfallidis** [comment]
Thank you for the information. So far, when I tried to use MSVC 2017 the Cython modules did not compile. @isuruf if you have MSVC 2017 in your machine can you try to compile dipy?
Clone this
```
https://github.com/nipy/dipy
```
and then do
```
cd dipy
pip install --user -e .
```
This works in my Win 10 - 64bit with Visual Build tools 2015 so if what Microsoft say is correct then it should compile just fine in VS 2017.
Thanks in advance.

**Comment by Garyfallidis** [comment]
@mwcraig in build tools there is no visual part where I can show an about box like the one you showed me. But as I said I installed build tools very recently so that link above should do the job if you try it.

Apologies for the urgency. But I would love to send an announcement saying that our conda package works in Win64 10. Please do help or suggest others who could help us with this.

**Comment by isuruf** [comment]
pyopencl also failed with Visual Studio 2015 Update 3. Solution was to switch to Visual Studio Update 2 by manually editing appveyor.yml. (Note that for python 3.6 the `CONDA_INSTALL_LOCN` variable has to be changed as well.)
cc https://github.com/conda-forge/pyopencl-feedstock/pull/1#issuecomment-258619268

**Comment by Garyfallidis** [comment]
@isuruf that means that we only need to add this line on top of the appveyor.yml file?
```
os:
  - Visual Studio 2015 Update 2
```
We already have the line
```
CONDA_INSTALL_LOCN: c:\\Miniconda36-x64
```

**Comment by isuruf** [comment]
`CONDA_INSTALL_LOCN: C:\\Miniconda36-x64`  has to be changed to `CONDA_INSTALL_LOCN: C:\\Miniconda35-x64` since there's no python 3.6 in the old appveyor image.

**Comment by arokem** [comment]
Is this what you meant? 

https://github.com/conda-forge/dipy-feedstock/pull/13/commits/0893822ff2d632296dd139db7ec364acdc534869

**Comment by isuruf** [comment]
Looks good to me.

Btw, I tried Visual Studio 2017 on appveyor and dipy builds fine, after patching conda-build for Visual Studio 2017 support.

**Comment by Garyfallidis** [comment]
Great news! The bots are building with update 2.
See here https://github.com/conda-forge/dipy-feedstock/pull/13
It would be great to have the VS 17 option. @isuruf can you share your appveyor configuration file for VS 17?

**Comment by isuruf** [comment]
I used `Visual Studio 2017` image on appveyor. Then RDPed to the server and patched conda-build. @msarahan, any plans on conda-build support for Visual Studio 2017?

**Comment by arokem** [comment]
Looks like packages are up on https://anaconda.org/conda-forge/dipy. 

I am closing this one.

**Comment by Garyfallidis** [comment]
Great first announcement to neuroimaging@python.org sent.

**Comment by Garyfallidis** [comment]
Will wait until Monday morning for any critical feedback and then send in all the relevant lists.

**Comment by isuruf** [comment]
FYI, switching to x86_amd64 compiler instead of amd64 fixed the compiler ICE.

**Comment by skoudoro** [comment]
👍
